version: "3.9"

services:
  web:
    build: .
    container_name: psiop_web
    restart: always
    environment:
      - FLASK_ENV=production
    expose:
      - "8000"
    networks:
      - psiop_net

  nginx:
    image: nginx:alpine
    container_name: psiop_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/psiop.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - psiop_net

networks:
  psiop_net:
    driver: bridge
